config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'users/profile', to: 'users#profile'
  get 'users/account', to: 'users#account'
  get 'users/profile/edit', to: 'users#edit_profile'
  patch 'users/profile', to: 'users#update_profile'

  resources :rooms do
    collection do
      get 'own' # ユーザーごとの部屋の一覧表示
    end
    resources :reservations, only: [:new, :create, :show, :destroy] do
      collection do
        get 'confirm'
      end
    end
  end

  # ユーザーが予約した部屋の一覧ページ用のルーティング
  get 'user_reservations', to: 'reservations#user_reservations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in, :check_out, :number_of_people, presence: true
  validate :check_out_after_check_in
  validates :number_of_people, numericality: { greater_than_or_equal_to: 1 }

  private
  def check_out_after_check_in
    return if check_out.blank? || check_in.blank?

    if check_out <= check_in
      errors.add(:check_out, 'はチェックイン日より後でなければなりません')
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :reservations
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :prefecture, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ProfileImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms
  has_many :reservations
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_room, only: [:new, :confirm, :create]
  before_action :authenticate_user!
  before_action :set_reservation, only: [:destroy]

  def user_reservations
    @reservations = current_user.reservations.includes(:room)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = @room.reservations.build
  end

  def confirm
    @reservation = @room.reservations.new(reservation_params)
    @reservation.user = current_user

    # 宿泊日数と合計金額の計算
    if @reservation.valid?
      number_of_nights = (@reservation.check_out - @reservation.check_in).to_i
      @total_price = @room.price * number_of_nights * @reservation.number_of_people
    else
      render 'rooms/show' and return
    end
  end



  def create
    @reservation = current_user.reservations.build(reservation_params.merge(room_id: @room.id))

    # 宿泊日数と合計金額の再計算
    if @reservation.check_in && @reservation.check_out
      number_of_nights = (@reservation.check_out - @reservation.check_in).to_i
      @reservation.total_price = @room.price * number_of_nights * @reservation.number_of_people
    end

    if @reservation.save
      redirect_to room_path(@room), notice: '予約が完了しました。'
    else
      flash.now[:alert] = '予約に失敗しました。'
      render 'rooms/show', status: :unprocessable_entity
    end
  end


  def edit
  end

  def update
  end

  def destroy
    @reservation.destroy
    redirect_to user_reservations_path, notice: '予約が削除されました。'
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :number_of_people, :room_id, :total_price)
  end

  def set_reservation
    @reservation = current_user.reservations.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :own, :show]

  def index
    if params[:prefecture].present? && params[:prefecture] != 'すべて'
      @rooms = Room.where(prefecture: params[:prefecture])
    else
      @rooms = Room.all
    end
  end

  def own
    @rooms = current_user.rooms
  end

  def show
    @room = Room.find(params[:id])
    @reservation = @room.reservations.build
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.new(room_params)
    if @room.save
      flash[:notice] = "施設の登録しました"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def room_params
    params.require(:room).permit(:name, :description, :price, :prefecture, :address, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:profile, :edit_profile, :update_profile, :account]

  def profile
    # プロフィール表示のロジック
    # @user には set_user メソッドで現在のユーザーがセットされています
  end

  def edit_profile
    # プロフィール編集ページの表示ロジック
    # @user には set_user メソッドで現在のユーザーがセットされています
  end

  def update_profile
    # プロフィール更新ロジック
    if @user.update(user_params)
      # 更新に成功した場合の処理
      redirect_to users_profile_path, notice: 'プロフィールが更新されました。'
    else
      # 更新に失敗した場合の処理
      render :edit_profile
    end
  end

  def account
  end


  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :icon, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="first-view">
  <div class="container">
    <h2 class="page-title">Potepan Shareで<br>まだ体験したことのない<br>旅をしよう</h2>
    <div class="search-form">
      <%= form_with(url: rooms_path, method: :get, local: true, html: { class: "form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.label :prefecture, "都道府県で検索", class: "form-label" %>
          <%= f.select :prefecture, ['北海道', '東京都', '大阪府', '京都府'], { include_blank: 'すべて' }, { class: "form-select" } %>
        </div>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <h3 class="recommendations-title">おすすめエリア</h3>
  <ul class="recommendations-list">
    <li class="recommendations-item tokyo">
      <%= link_to rooms_path(prefecture: '東京都'), class: "recommendations-link" do %>
        <span class="prefecture-name">東京都</span>
      <% end %>
    </li>
    <li class="recommendations-item osaka">
      <%= link_to rooms_path(prefecture: '大阪府'), class: "recommendations-link" do %>
        <span class="prefecture-name">大阪府</span>
      <% end %>
    </li>
    <li class="recommendations-item kyoto">
      <%= link_to rooms_path(prefecture: '京都府'), class: "recommendations-link" do %>
        <span class="prefecture-name">京都府</span>
      <% end %>
    </li>
    <li class="recommendations-item hokkaido">
      <%= link_to rooms_path(prefecture: '北海道'), class: "recommendations-link" do %>
        <span class="prefecture-name">北海道</span>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LodgmentReservationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/reservations/confirm.html.erb
<h1>予約確認</h1>


<%= form_with(model: [@room, @reservation], url: room_reservations_path(@room), method: :post) do |f| %>
  <p>チェックイン日: <%= @reservation.check_in %></p>
  <p>チェックアウト日: <%= @reservation.check_out %></p>
  <p>人数: <%= @reservation.number_of_people %></p>
  <p>合計金額: <%= @total_price %></p>

  <%= f.hidden_field :check_in, value: @reservation.check_in %>
  <%= f.hidden_field :check_out, value: @reservation.check_out %>
  <%= f.hidden_field :number_of_people, value: @reservation.number_of_people %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :total_price, value: @total_price %>

  <%= f.submit "この内容で予約する" %>
<% end %>

app/views/reservations/user_reservations.html.erb
<h1>予約一覧</h1>

<table class="room-table">
  <thead>
    <tr>
      <th class="room-header">画像</th>
      <th class="room-header">施設名</th>
      <th class="room-header">紹介文</th>
      <th class="room-header">合計料金</th>
      <th class="room-header">チェックイン</th>
      <th class="room-header">チェックアウト</th>
      <th class="room-header">予約確定日時</th>
      <th class="room-header">操作</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td class="room-data">
          <%= image_tag reservation.room.image.url, class: "room-image" %>
        </td>
        <td class="room-data"><%= reservation.room.name %></td>
        <td class="room-data"><%= reservation.room.description %></td>
        <td class="room-data"><%= reservation.total_price %></td>
        <td class="room-data"><%= reservation.check_in.strftime("%Y/%m/%d") %></td>
        <td class="room-data"><%= reservation.check_out.strftime("%Y/%m/%d") %></td>
        <td class="room-data"><%= reservation.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td class="room-data">
          <%= link_to '削除', room_reservation_path(reservation.room, reservation), method: :delete, data: { confirm: '予約を削除してよろしいですか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/index.html.erb
<div class="container">
  <%= render 'shared/room_table' %>

  <%= form_with(url: rooms_path, method: :get, local: true) do |f| %>
    <%= f.label :prefecture, "都道府県で検索" %>
    <%= f.select :prefecture, ['北海道', '東京都', '大阪府', '京都府'], include_blank: 'すべて' %>
    <%= f.submit "検索" %>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h2>新規登録</h2>

<%= render "shared/error", obj: @room %>

<%= form_with model: @room do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br/>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :prefecture, "都道府県" %><br/>
    <%= f.select :prefecture, ['北海道', '東京都', '大阪府', '京都府'], include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>



  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/rooms/own.html.erb
<%= link_to '施設の新規登録', new_room_path %>

<h2>登録済み一覧</h2>
<%= render 'shared/room_table' %>

<%= form_with(url: rooms_path, method: :get, local: true) do |f| %>
  <%= f.label :prefecture, "都道府県で検索" %>
  <%= f.select :prefecture, ['北海道', '東京都', '大阪府', '京都府'], include_blank: 'すべて' %>
  <%= f.submit "検索" %>
<% end %>

app/views/rooms/show.html.erb
<% if @reservation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
    <ul>
    <% @reservation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= link_to '戻る', root_path %>
<p>
  <%= image_tag @room.image.url %>
</p>
<p>
  <%= @room.name %>
</p>
<p>
  <%= @room.description %>
</p>
<p>
  <%= @room.price %>
</p>
<p>
  <%= @room.address %>
</p>
<p>
  <%= @room.description %>
</p>

<%= form_with url: confirm_room_reservations_path(@room), method: :get, local: true, scope: :reservation do |f| %>
  <div class="field">
    <%= f.label :check_in, "チェックイン日" %>
    <%= f.date_field :check_in %>
  </div>
  <div class="field">
    <%= f.label :check_out, "チェックアウト日" %>
    <%= f.date_field :check_out %>
  </div>
  <div class="field">
    <%= f.label :number_of_people, "人数" %>
    <%= f.number_field :number_of_people %>
  </div>
  <div class="actions">
    <%= f.submit "予約確認" %>
  </div>
<% end %>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer-logo">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', alt: 'サイトロゴ' %>
      <% end %>
    </div>
    <p class="footer-copyright">
      Copyright © Potepan Share 2024 All rights reserved
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', alt: 'サイトロゴ' %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="header-logged-in">
      <div class="user-trigger">
        <%= image_tag current_user.profile_image.url, alt: 'プロフィール画像', class: 'profile-image' %>
        <span class="user-name"><%= current_user.name %></span>
        <div class="dropdown-content">
          <%= link_to '施設の新規登録', new_room_path %>
          <%= link_to '予約一覧', user_reservations_path %>
          <%= link_to '登録済み一覧', own_rooms_path %>
          <%= link_to 'アカウント設定', users_account_path %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="header-logged-out">
      <%= link_to 'ログイン', new_user_session_path %>
      <%= link_to '新規登録', new_user_registration_path, class: 'register-link' %>
    </div>
  <% end %>
</header>

app/views/shared/_room_table.html.erb
<table class="room-table">
  <thead>
    <tr>
      <th class="room-header">画像</th>
      <th class="room-header">施設名</th>
      <th class="room-header">住所</th>
      <th class="room-header">紹介文</th>
      <th class="room-header">料金</th>
      <th class="room-header">作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td class="room-data"><%= image_tag room.image.url, class: "room-image" %></td>
        <td class="room-data"><%= link_to room.name, room %></td>
        <td class="room-data"><%= room.prefecture %></td>
        <td class="room-data"><%= room.description %></td>
        <td class="room-data"><%= room.price %></td>
        <td class="room-data"><%= room.updated_at.to_s(:short) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/account.html.erb
<div class="container">
  <h2 class="account-title">アカウント</h2>
  <div class="account-info">
    <% if current_user %>
      <p class="text-info">メールアドレス: <%= current_user.email %></p>
      <p class="text-info">パスワード: ******</p>
    <% else %>
      <p class="text-info">ログインしていません。</p>
    <% end %>
  </div>

  <div class="account-actions">
    <%= link_to '編集', edit_user_registration_path, class: "action-link" %>
    <%= link_to 'プロフィール', users_profile_path, class: "action-link" %>
  </div>
</div>

app/views/users/edit_profile.html.erb
<div class="container">
  <h2 class="account-title">プロフィール編集ページ</h2>
  <%= form_with model: @user, url: users_profile_path, method: :patch, local: true, html: { multipart: true, class: "profile-form" } do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "form-label" %><br/>
      <%= f.text_field :name, autofocus: true, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= f.label :introduction, class: "form-label" %><br/>
      <%= f.text_area :introduction, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= f.label :profile_image, class: "form-label" %><br/>
      <%= f.file_field :profile_image, class: "form-input" %>
    </div>

    <div class="form-actions">
      <%= f.submit "保存", class: "action-link" %>
      <%= link_to 'キャンセル', users_profile_path, class: "action-link" %>
    </div>
  <% end %>
</div>

app/views/users/profile.html.erb
<div class="container">
  <h2 class="account-title">プロフィール</h2>
  <div class="profile-info">
    <div class="profile-info-item">
      <span class="text-label">アイコン画像:</span>
      <%= image_tag @user.profile_image.url, class: "profile-image" %>
    </div>
    <p class="text-info">名前: <%= @user.name %></p>
    <p class="text-info">自己紹介: <%= @user.introduction %></p>
  </div>

  <div class="profile-actions">
    <%= link_to '編集', users_profile_edit_path, class: "action-link" %>
    <%= link_to 'アカウント', users_account_path, class: "action-link" %>
  </div>
</div>